export const REQUESE_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';

export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_EXACT_ARTICLES = 'FETCH_EXACT_ARTICLES';
