export const REQUESE_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';

export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_EXACT_ARTICLES = 'FETCH_EXACT_ARTICLES';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
